# High-value dataset categories by url
# fetched from https://publications.europa.eu/resource/authority/bna/asd487ae75
# on 2025-03-24

url_title_map = {
    "http://data.europa.eu/bna/c_164e0bf5": "Meteorological",
    "http://data.europa.eu/bna/c_a9135398": "Companies and company ownership",
    "http://data.europa.eu/bna/c_ac64a52d": "Geospatial",
    "http://data.europa.eu/bna/c_b79e35eb": "Mobility",
    "http://data.europa.eu/bna/c_dd313021": "Earth observation and environment",
    "http://data.europa.eu/bna/c_e1da4e07": "Statistics",
    "http://data.europa.eu/bna/c_03ba8d92": "Regular lock and bridge operating times",
    "http://data.europa.eu/bna/c_04bf94a3": "Poverty",
    "http://data.europa.eu/bna/c_06b1eec4": "Hydrography",
    "http://data.europa.eu/bna/c_1226dc1a": "Bank of waterway at mean water level",
    "http://data.europa.eu/bna/c_13e3cf16": "NWP model data",
    "http://data.europa.eu/bna/c_1e787364": "Reference data for water level gauges relevant to navigation",
    "http://data.europa.eu/bna/c_2037ada4": "Navigation rules and recommendations",
    "http://data.europa.eu/bna/c_20cd11bb": "EU International trade in goods statistics – exports and imports breakdowns simultaneously by partner, product and flow",
    "http://data.europa.eu/bna/c_23385471": "Potential labour force",
    "http://data.europa.eu/bna/c_25f43866": "Rates of waterway infrastructure charges",
    "http://data.europa.eu/bna/c_298ffb73": "Links to the external xml-files with operation times of restricting structures",
    "http://data.europa.eu/bna/c_2aed31f9": "Industrial producer price index breakdowns by activity",
    "http://data.europa.eu/bna/c_315692ad": "Elevation",
    "http://data.europa.eu/bna/c_317b9493": "Population, Fertility, Mortality",
    "http://data.europa.eu/bna/c_34abf8c1": "Industrial production",
    "http://data.europa.eu/bna/c_36807466": "Climate data: validated observations",
    "http://data.europa.eu/bna/c_38933a65": "Waste",
    "http://data.europa.eu/bna/c_3af3368c": "Observations data measured by weather stations",
    "http://data.europa.eu/bna/c_3e8e3bf7": "Location and characteristics of ports and transhipment sites",
    "http://data.europa.eu/bna/c_407951ff": "Location of ports and transhipment sites",
    "http://data.europa.eu/bna/c_424bb0b4": "Current healthcare expenditure",
    "http://data.europa.eu/bna/c_43f88346": "Water",
    "http://data.europa.eu/bna/c_4ac557e7": "Government expenditure and revenue",
    "http://data.europa.eu/bna/c_4acb6bf3": "Mortality",
    "http://data.europa.eu/bna/c_4b74ea13": "Transport networks",
    "http://data.europa.eu/bna/c_4ba9548e": "Emissions",
    "http://data.europa.eu/bna/c_4d63300b": "Horizontal legislation",
    "http://data.europa.eu/bna/c_4dd389c5": "Mineral resources",
    "http://data.europa.eu/bna/c_56a1bf47": "Basic company information: key attributes",
    "http://data.europa.eu/bna/c_593bc53d": "Short term changes of aids to navigation",
    "http://data.europa.eu/bna/c_59627af3": "National accounts – key indicators on households",
    "http://data.europa.eu/bna/c_59c93ba5": "Production and industrial facilities",
    "http://data.europa.eu/bna/c_59e64dd4": "Climate",
    "http://data.europa.eu/bna/c_60182062": "Buildings",
    "http://data.europa.eu/bna/c_63b37dd4": "Air",
    "http://data.europa.eu/bna/c_63be22bd": "Natural risk zones",
    "http://data.europa.eu/bna/c_642643e6": "Agricultural parcels",
    "http://data.europa.eu/bna/c_664c9e5a": "Boundaries of the fairway/navigation channel",
    "http://data.europa.eu/bna/c_66b946cb": "Short term changes of lock and bridge operating times",
    "http://data.europa.eu/bna/c_6a3f6896": "Cadastral parcels",
    "http://data.europa.eu/bna/c_6a7250c1": "Fertility",
    "http://data.europa.eu/bna/c_6c2bb82d": "Geographical names",
    "http://data.europa.eu/bna/c_793164b6": "Species distribution",
    "http://data.europa.eu/bna/c_7b8fbb64": "Environmental monitoring facilities",
    "http://data.europa.eu/bna/c_7e19ef26": "Other physical limitations on waterways",
    "http://data.europa.eu/bna/c_83aa10a6": "Protected sites",
    "http://data.europa.eu/bna/c_87a129d9": "Soil",
    "http://data.europa.eu/bna/c_883d0205": "Contours of locks and dams",
    "http://data.europa.eu/bna/c_8f0fac04": "Company documents and accounts",
    "http://data.europa.eu/bna/c_91185a85": "Orthoimagery",
    "http://data.europa.eu/bna/c_92874eb2": "Environmental accounts and statistics",
    "http://data.europa.eu/bna/c_9427236f": "Administrative units",
    "http://data.europa.eu/bna/c_95da87c7": "National accounts – key indicators on corporations",
    "http://data.europa.eu/bna/c_99bc517f": "Isolated dangers in the fairway/navigation channel under and above water",
    "http://data.europa.eu/bna/c_9cbe4435": "List of navigation aids and traffic signs",
    "http://data.europa.eu/bna/c_a2c6dcd8": "Employment",
    "http://data.europa.eu/bna/c_a3767648": "Tourism flows in Europe",
    "http://data.europa.eu/bna/c_a49ec591": "Volume of sales by activity",
    "http://data.europa.eu/bna/c_a8b937c4": "Inequality",
    "http://data.europa.eu/bna/c_ad9ae929": "Land use",
    "http://data.europa.eu/bna/c_af646f5b": "Area management / restriction / regulation zones & reporting units",
    "http://data.europa.eu/bna/c_b121e2f6": "Temporary obstructions in the fairway",
    "http://data.europa.eu/bna/c_b151a0ba": "Inland waterways datasets",
    "http://data.europa.eu/bna/c_b21e1296": "Land cover",
    "http://data.europa.eu/bna/c_b24028d7": "Official aids-to-navigation (e.g. buoys, beacons, lights, notice marks)",
    "http://data.europa.eu/bna/c_b40e6d46": "Oceanographic geographical features",
    "http://data.europa.eu/bna/c_b72b721f": "National accounts – GDP main aggregates",
    "http://data.europa.eu/bna/c_b7de66cd": "Energy resources",
    "http://data.europa.eu/bna/c_b7f6a4f3": "Nature preservation and biodiversity",
    "http://data.europa.eu/bna/c_bc8941d9": "Shoreline construction",
    "http://data.europa.eu/bna/c_be47b010": "Weather alerts",
    "http://data.europa.eu/bna/c_c0022235": "Harmonised Indices of consumer prices",
    "http://data.europa.eu/bna/c_c19af83a": "Waterway axis with kilometres indication",
    "http://data.europa.eu/bna/c_c3919aec": "Habitats and biotopes",
    "http://data.europa.eu/bna/c_c3de25e4": "Addresses",
    "http://data.europa.eu/bna/c_c873f344": "Bio-geographical regions",
    "http://data.europa.eu/bna/c_d13a4420": "Radar data",
    "http://data.europa.eu/bna/c_dd8f4797": "Consolidated government gross debt",
    "http://data.europa.eu/bna/c_e3f55603": "Geology",
    "http://data.europa.eu/bna/c_e4358335": "Noise",
    "http://data.europa.eu/bna/c_e50004c6": "State of the rivers, canals, locks and bridges",
    "http://data.europa.eu/bna/c_e5f69a04": "Present and future water levels at gauges",
    "http://data.europa.eu/bna/c_f2b50efd": "Population",
    "http://data.europa.eu/bna/c_f399050e": "Sea regions",
    "http://data.europa.eu/bna/c_f6886b00": "Restrictions caused by flood and ice",
    "http://data.europa.eu/bna/c_f76b01e6": "Fairway characteristics",
    "http://data.europa.eu/bna/c_fa2a1c3a": "Long-time obstructions in the fairway and reliability",
    "http://data.europa.eu/bna/c_fbd2fc3f": "Reference parcels",
    "http://data.europa.eu/bna/c_fd4e881c": "Unemployment",
    "http://data.europa.eu/bna/c_fef208ab": "Water depths contours in the navigation channel",
}
